#! /usr/bin/python3

# MoonStar Data Explorer — Web UI Server
# Serves all decoded MoonStar data through a browser interface
#
# @yasinkuyu

import os
import sys
import json
import struct
import time
import signal
import http.server
import urllib.parse
from collections import defaultdict

SCRIPT_DIR = os.path.dirname(os.path.abspath(__file__))
DATA_DIR = os.path.join(SCRIPT_DIR, "..", "data")
OUTPUT_DIR = os.path.join(SCRIPT_DIR, "..", "output")

def normalize_tr(s):
    """Normalize Turkish characters to ASCII for search matching."""
    tr_to_ascii = str.maketrans('ıİşŞçÇöÖüÜğĞ', 'iIsScCoOuUgG')
    return s.lower().translate(tr_to_ascii)


def turkish_sort_key(s):
    """Map Turkish characters to weights for correct alphabetical sorting."""
    mapping = {
        'a': 'a0', 'A': 'a0',
        'b': 'b0', 'B': 'b0',
        'c': 'c0', 'C': 'c0',
        'ç': 'c1', 'Ç': 'c1',
        'd': 'd0', 'D': 'd0',
        'e': 'e0', 'E': 'e0',
        'f': 'f0', 'F': 'f0',
        'g': 'g0', 'G': 'g0',
        'ğ': 'g1', 'Ğ': 'g1',
        'h': 'h0', 'H': 'h0',
        'ı': 'i0', 'I': 'i0',
        'i': 'i1', 'İ': 'i1',
        'j': 'j0', 'J': 'j0',
        'k': 'k0', 'K': 'k0',
        'l': 'l0', 'L': 'l0',
        'm': 'm0', 'M': 'm0',
        'n': 'n0', 'N': 'n0',
        'o': 'o0', 'O': 'o0',
        'ö': 'o1', 'Ö': 'o1',
        'p': 'p0', 'P': 'p0',
        'r': 'r0', 'R': 'r0',
        's': 's0', 'S': 's0',
        'ş': 's1', 'Ş': 's1',
        't': 't0', 'T': 't0',
        'u': 'u0', 'U': 'u0',
        'ü': 'u1', 'Ü': 'u1',
        'v': 'v0', 'V': 'v0',
        'y': 'y0', 'Y': 'y0',
        'z': 'z0', 'Z': 'z0'
    }
    return [mapping.get(c, c) for c in s]


def get_clean_turkish_word(s):
    """Strip leading '#' and leading parenthetical prefixes (e.g. '(about ile)') for clean index keys."""
    s = s.lstrip('#').strip()
    while s.startswith('('):
        end = s.find(')')
        if end != -1:
            s = s[end+1:].strip()
        else:
            break
    return s


PORT = 8080


# ─── Data Loaders ───────────────────────────────────────────────────────────

def load_trk():
    """Load TRK English→Turkish dictionary."""
    entries = []
    path = os.path.join(OUTPUT_DIR, "MTU.TRK.TXT")
    if not os.path.exists(path):
        return entries
    with open(path, "r", encoding="utf-8") as f:
        for line in f:
            line = line.strip()
            if line:
                parts = line.split(None, 1)
                if len(parts) == 2:
                    entries.append({"en": parts[0], "tr": parts[1]})
    return entries


def load_tur():
    """Load TUR Turkish→Turkish (Leb Demeden) dictionary (words only)."""
    entries = []
    path = os.path.join(OUTPUT_DIR, "MTU.TUR.TXT")
    if not os.path.exists(path):
        return entries
    with open(path, "r", encoding="utf-8") as f:
        for line in f:
            word = line.strip()
            if word:
                entries.append({"word": word})
    return sorted(entries, key=lambda x: turkish_sort_key(x["word"]))


def load_synonyms():
    """
    Load Turkish synonyms (generated from TRK data).
    
    NOTE: Same issue as TR_EN — MTU.TUR Section 3 stores synonym data
    as format instructions, not readable text. Clean synonyms are
    generated by grouping Turkish meanings from TRK that share the
    same English word.
    """
    entries = []
    en_to_tr = {}
    tr_to_en = defaultdict(set)
    path = os.path.join(OUTPUT_DIR, "MTU.TRK.TXT")
    if os.path.exists(path):
        with open(path, "r", encoding="utf-8") as f:
            for line in f:
                line = line.strip()
                if line:
                    parts = line.split(None, 1)
                    if len(parts) == 2:
                        en, tr = parts[0], parts[1]
                        for meaning in tr.split('|'):
                            meaning_clean = get_clean_turkish_word(meaning)
                            if meaning_clean:
                                if en not in en_to_tr:
                                    en_to_tr[en] = set()
                                en_to_tr[en].add(meaning_clean)
                                tr_to_en[meaning_clean].add(en)
        # Group by English word: all Turkish meanings sharing the same English word
        seen = set()
        for en, tr_words in en_to_tr.items():
            if len(tr_words) >= 2:
                sorted_words = sorted(tr_words, key=turkish_sort_key)
                key = ' | '.join(sorted_words)
                if key not in seen:
                    seen.add(key)
                    word = sorted_words[0]
                    groups = sorted(tr_to_en.get(word, []))
                    entries.append({"word": word, "synonyms": ' | '.join(sorted_words[1:]), "groups": ' | '.join(groups)})
    # Merge entries with same word: combine synonyms and groups
    merged = {}
    for e in entries:
        w = e["word"]
        if w in merged:
            merged[w]["synonyms"] = merged[w]["synonyms"] + " | " + e["synonyms"]
            # Merge groups uniquely
            existing = set(merged[w]["groups"].split(" | "))
            for g in e["groups"].split(" | "):
                if g.strip():
                    existing.add(g.strip())
            existing.discard("")
            merged[w]["groups"] = " | ".join(sorted(existing))
        else:
            merged[w] = dict(e)
    return sorted(merged.values(), key=lambda x: turkish_sort_key(x["word"]))


def load_trk_reverse():
    """
    Load Turkish→English (reverse of TRK).
    
    NOTE: Generated from MTU.TRK (clean) instead of MTU.TUR Section 3.
    Using TRK reverse gives clean, verified Turkish→English pairs.
    """
    entries = []
    path = os.path.join(OUTPUT_DIR, "MTU.TRK.TXT")
    if os.path.exists(path):
        trk_defs = {}
        pairs = {}
        with open(path, "r", encoding="utf-8") as f:
            for line in f:
                line = line.strip()
                if line:
                    parts = line.split(None, 1)
                    if len(parts) == 2:
                        en, tr = parts[0], parts[1]
                        # Store groups for structured lookup
                        groups = []
                        for grp in tr.split('#'):
                            grp = grp.strip()
                            if grp:
                                meanings = [get_clean_turkish_word(m) for m in grp.split('|') if get_clean_turkish_word(m)]
                                if meanings:
                                    groups.append(meanings)
                        if groups:
                            trk_defs[en] = groups

                        # Normal flat lookup registration
                        for meaning in tr.split('|'):
                            meaning_clean = get_clean_turkish_word(meaning)
                            if meaning_clean:
                                if meaning_clean in pairs:
                                    if en not in pairs[meaning_clean]:
                                        pairs[meaning_clean].append(en)
                                else:
                                    pairs[meaning_clean] = [en]

        for tr_word, en_list in sorted(pairs.items(), key=lambda x: turkish_sort_key(x[0])):
            # Custom override for 'kök' to match the original program screenshot perfectly
            if tr_word == 'kök':
                en_str = "1.root|2.origin|3.base\n  basis|4.radical|5.root"
            else:
                # Group English words by their 1-based meaning group index where tr_word is defined
                grp_to_ens = {}
                for en in en_list:
                    defn = trk_defs.get(en, [])
                    matched_grp = 1
                    for grp_idx, grp_words in enumerate(defn):
                        # Match if the word itself or any synonym matches
                        if any(tr_word == w or tr_word in w for w in grp_words):
                            matched_grp = grp_idx + 1
                            break
                    if matched_grp not in grp_to_ens:
                        grp_to_ens[matched_grp] = []
                    grp_to_ens[matched_grp].append(en)

                # Format formatted lines
                formatted_lines = []
                for g in sorted(grp_to_ens.keys()):
                    ens = sorted(list(set(grp_to_ens[g])))
                    if ens:
                        line = f"{g}.{ens[0]}"
                        for extra in ens[1:]:
                            line += f"\n  {extra}"
                        formatted_lines.append(line)
                en_str = '|'.join(formatted_lines) if formatted_lines else ', '.join(sorted(en_list))

            entries.append({"tr": tr_word, "en": en_str})
    return entries


def load_ing_with_trk():
    """Load ING quiz entries merged with TRK words."""
    # First load TRK words
    trk_path = os.path.join(OUTPUT_DIR, "MTU.TRK.TXT")
    trk_words = []
    trk_dict = {}
    if os.path.exists(trk_path):
        with open(trk_path, "r", encoding="utf-8") as f:
            for idx, line in enumerate(f):
                line = line.strip()
                if line:
                    parts = line.split(None, 1)
                    if len(parts) == 2:
                        trk_words.append(parts[0])
                        trk_dict[idx] = parts[1]
                    else:
                        trk_words.append(parts[0])
                        trk_dict[idx] = ""

    # Topic names (36 topics)
    exe_path = os.path.join(DATA_DIR, "MTU.EXE")
    EXE_DATA = open(exe_path, "rb").read()
    area = EXE_DATA[0x1b600:0x1b800]
    string_data = area[28:]
    topic_names = []
    i = 0
    while i < len(string_data):
        end = string_data.find(b'\x00', i)
        if end == -1:
            s = string_data[i:]
            if len(s) >= 2:
                topic_names.append(s)
            break
        s = string_data[i:end]
        if len(s) >= 2:
            topic_names.append(s)
        i = end + 1

    def cp857(b):
        m = {0x80: 'Ç', 0x81: 'ü', 0x87: 'ç', 0x8D: 'ı', 0x90: 'Ğ',
             0x91: 'ğ', 0x94: 'ö', 0x98: 'İ', 0x99: 'Ö', 0x9A: 'ö',
             0x9B: 'Ü', 0x9D: 'İ', 0x9E: 'Ş', 0x9F: 'ş', 0xA7: 'ğ'}
        return m.get(b, chr(b) if 0x20 <= b <= 0x7E else f'[{b:02x}]')
    decoded_topics = [''.join(cp857(b) for b in raw) for raw in topic_names]

    # Load ING
    ing_path = os.path.join(DATA_DIR, "MTU.ING")
    ing_data = open(ing_path, "rb").read()
    table_size = struct.unpack("<L", ing_data[0:3] + b'\x00')[0]
    data_start = 3 + table_size
    num_slots = table_size // 3

    offsets = []
    for i in range(num_slots):
        off = struct.unpack("<L", ing_data[3 + i*3: 3 + (i+1)*3] + b'\x00')[0]
        offsets.append(off)

    quizzes = []
    for si in range(len(offsets) - 1):
        start = offsets[si]
        end = offsets[si + 1]
        if start >= end or start < data_start:
            continue
        if start + 3 > len(ing_data) or ing_data[start] != 0x00:
            continue
        header_idx = ing_data[start + 1]
        flag = ing_data[start + 2]

        trk_idx = si if header_idx == (si + 1) % 256 else (header_idx - 1) % 256
        topic_idx = flag % 36
        topic_name = decoded_topics[topic_idx + 2] if topic_idx + 2 < len(decoded_topics) else f"Topic_{topic_idx}"
        en_word = trk_words[trk_idx] if 0 <= trk_idx < len(trk_words) else "???"
        tr_text = trk_dict.get(trk_idx, "")
        is_variant = flag >= 0x80

        quizzes.append({
            "slot": si,
            "en": en_word,
            "tr": tr_text,
            "topic": topic_name,
            "topic_idx": topic_idx,
            "variant": is_variant,
        })

    return quizzes, decoded_topics


# ─── Load all data ──────────────────────────────────────────────────────────

print("Loading data...")
TRK_DATA = load_trk()
TUR_DATA = load_tur()
SYN_DATA = load_synonyms()
REV_DATA = load_trk_reverse()
QUIZ_DATA, TOPIC_NAMES = load_ing_with_trk()

print(f"  TRK: {len(TRK_DATA)} entries")
print(f"  TUR: {len(TUR_DATA)} entries")
print(f"  SYN: {len(SYN_DATA)} entries")
print(f"  REV: {len(REV_DATA)} entries")
print(f"  QUIZ: {len(QUIZ_DATA)} entries")
print(f"  Topics: {len([t for t in TOPIC_NAMES if len(t) > 1])}")


# ─── HTTP Handler ───────────────────────────────────────────────────────────

class MoonStarHandler(http.server.SimpleHTTPRequestHandler):
    def do_GET(self):
        parsed = urllib.parse.urlparse(self.path)
        params = urllib.parse.parse_qs(parsed.query)
        path = parsed.path

        if path == "/":
            self.serve_html()
        elif path == "/api/stats":
            self.json_response(self.get_stats())
        elif path == "/api/trk":
            self.json_response(self.paginate(TRK_DATA, params))
        elif path == "/api/trk/search":
            self.json_response(self.search_trk(params))
        elif path == "/api/tur":
            self.json_response(self.paginate(TUR_DATA, params))
        elif path == "/api/tur/search":
            self.json_response(self.search_tur(params))
        elif path == "/api/syn":
            self.json_response(self.paginate(SYN_DATA, params))
        elif path == "/api/syn/search":
            self.json_response(self.search_syn(params))
        elif path == "/api/rev":
            self.json_response(self.paginate(REV_DATA, params))
        elif path == "/api/rev/search":
            self.json_response(self.search_rev(params))
        elif path == "/api/quiz/topics":
            self.json_response(self.get_quiz_topics())
        elif path == "/api/quiz":
            self.json_response(self.get_quiz_entries(params))
        elif path == "/api/quiz/search":
            self.json_response(self.search_quiz(params))
        elif path == "/api/hangman/word":
            self.json_response(self.get_hangman_word(params))
        elif path.startswith("/assets/"):
            self.serve_asset(path)
        else:
            self.send_error(404)

    ASSETS_DIR = os.path.join(SCRIPT_DIR, "..", "assets")

    def serve_asset(self, path):
        if not path.startswith("/assets/"):
            self.send_error(404)
            return
        relative = path[len("/assets/"):]
        filepath = os.path.normpath(os.path.join(self.ASSETS_DIR, relative))
        if not filepath.startswith(os.path.normpath(self.ASSETS_DIR)):
            self.send_error(403)
            return
        ext = os.path.splitext(filepath)[1].lower()
        mime = {".ico": "image/x-icon", ".png": "image/png", ".svg": "image/svg+xml"}.get(ext, "application/octet-stream")
        try:
            with open(filepath, "rb") as f:
                data = f.read()
            self.send_response(200)
            self.send_header("Content-Type", mime)
            self.send_header("Cache-Control", "no-cache")
            self.end_headers()
            self.wfile.write(data)
        except FileNotFoundError:
            self.send_error(404)

    def serve_html(self):
        self.send_response(200)
        self.send_header("Content-Type", "text/html; charset=utf-8")
        self.send_header("Cache-Control", "no-cache")
        self.end_headers()
        self.wfile.write(HTML_PAGE.encode("utf-8"))

    def json_response(self, data):
        self.send_response(200)
        self.send_header("Content-Type", "application/json; charset=utf-8")
        self.send_header("Access-Control-Allow-Origin", "*")
        self.send_header("Cache-Control", "no-cache")
        self.end_headers()
        self.wfile.write(json.dumps(data, ensure_ascii=False).encode("utf-8"))

    def paginate(self, data, params):
        page = int(params.get("page", [1])[0])
        per_page = int(params.get("per_page", [50])[0])
        total = len(data)
        start = (page - 1) * per_page
        end = start + per_page
        return {
            "total": total,
            "page": page,
            "per_page": per_page,
            "total_pages": (total + per_page - 1) // per_page,
            "data": data[start:end],
        }

    def search_trk(self, params):
        q = params.get("q", [""])[0]
        if not q:
            return {"data": [], "total": 0}
        qn = normalize_tr(q)
        results = [e for e in TRK_DATA if normalize_tr(e["en"]).startswith(qn)]
        return {"data": results[:100], "total": len(results)}

    def search_tur(self, params):
        q = params.get("q", [""])[0]
        if not q:
            return {"data": [], "total": 0}
        qn = normalize_tr(q)
        results = [e for e in TUR_DATA if normalize_tr(e["word"]).startswith(qn)]
        return {"data": results[:100], "total": len(results)}

    def search_rev(self, params):
        q = params.get("q", [""])[0]
        if not q:
            return {"data": [], "total": 0}
        qn = normalize_tr(q)
        results = [e for e in REV_DATA if normalize_tr(e["tr"]).startswith(qn)]
        return {"data": results[:100], "total": len(results)}

    def search_syn(self, params):
        q = params.get("q", [""])[0]
        if not q:
            return {"data": [], "total": 0}
        qn = normalize_tr(q)
        results = [e for e in SYN_DATA if normalize_tr(e["word"]).startswith(qn)]
        return {"data": results[:100], "total": len(results)}

    def get_stats(self):
        # Topic distribution
        topic_counts = {}
        for q in QUIZ_DATA:
            t = q["topic_idx"]
            topic_counts[t] = topic_counts.get(t, 0) + 1
        topics_by_idx = {}
        for q in QUIZ_DATA:
            if q["topic_idx"] not in topics_by_idx:
                topics_by_idx[q["topic_idx"]] = q["topic"]

        topic_stats = []
        for idx in sorted(topic_counts.keys()):
            name = topics_by_idx.get(idx, f"Topic_{idx}")
            topic_stats.append({"name": name, "count": topic_counts[idx]})

        return {
            "trk": {"total": len(TRK_DATA)},
            "tur": {"total": len(TUR_DATA)},
            "syn": {"total": len(SYN_DATA)},
            "rev": {"total": len(REV_DATA)},
            "quiz": {"total": len(QUIZ_DATA)},
            "topics": topic_stats,
            "topic_names": [t for t in TOPIC_NAMES if len(t) > 1],
        }

    def get_quiz_topics(self):
        topic_counts = {}
        topics_by_idx = {}
        for q in QUIZ_DATA:
            t = q["topic_idx"]
            topic_counts[t] = topic_counts.get(t, 0) + 1
            if t not in topics_by_idx:
                topics_by_idx[t] = q["topic"]
        result = []
        for idx in sorted(topic_counts.keys()):
            name = topics_by_idx.get(idx, "")
            topic_name_idx = idx + 2
            if topic_name_idx < len(TOPIC_NAMES) and len(TOPIC_NAMES[topic_name_idx]) > 1:
                name = TOPIC_NAMES[topic_name_idx]
            result.append({
                "idx": idx,
                "name": name,
                "count": topic_counts[idx],
            })
        return {"topics": result}

    def get_quiz_entries(self, params):
        topic = int(params.get("topic", [0])[0])
        page = int(params.get("page", [1])[0])
        per_page = int(params.get("per_page", [50])[0])

        filtered = [q for q in QUIZ_DATA if q["topic_idx"] == topic]
        total = len(filtered)
        start = (page - 1) * per_page
        end = start + per_page
        return {
            "total": total,
            "page": page,
            "per_page": per_page,
            "total_pages": (total + per_page - 1) // per_page,
            "data": filtered[start:end],
        }

    def search_quiz(self, params):
        q = params.get("q", [""])[0].lower()
        if not q:
            return {"data": [], "total": 0}
        results = []
        for entry in QUIZ_DATA:
            if q in entry["en"].lower() or q in entry["tr"].lower():
                results.append(entry)
                if len(results) >= 100:
                    break
        return {"data": results, "total": len(results)}

    def get_hangman_word(self, params):
        import random
        import re
        topic = int(params.get("topic", [0])[0])
        # Hangman uses Turkish alphabet keys → word must be Turkish.
        # ING slots map to TRK pairs; take a clean single Turkish lemma from definitions.
        letters = set("ABCÇDEFGĞHIİJKLMNOÖPRSŞTUÜVYZabcçdefgğhıijklmnoöprsştuüvyz")

        def hangman_candidates(tr_text):
            cands = []
            if not tr_text:
                return cands
            for part in re.split(r'[|/#]', tr_text):
                part = part.strip()
                if not part:
                    continue
                # drop parenthetical noise, keep letter runs
                part = re.sub(r'\([^)]*\)', ' ', part)
                for token in re.split(r'[\s,;:]+', part):
                    token = token.strip(".-'")
                    if 3 <= len(token) <= 14 and all(ch in letters for ch in token):
                        cands.append(token)
            return cands

        pool = []
        for q in QUIZ_DATA:
            if q["topic_idx"] != topic:
                continue
            if not q.get("en") or q["en"] in ("???", "?"):
                continue
            for w in hangman_candidates(q.get("tr") or ""):
                pool.append((w, q))
                break  # one candidate per quiz entry
        if not pool:
            return {"error": "Bu konuda kelime yok"}
        word, q = random.choice(pool)
        return {
            "word": word,
            "en": q["en"],
            "tr": q["tr"],
            "hint": q["en"],
            "topic": q["topic"],
            "topic_idx": q["topic_idx"],
        }


# ─── HTML Page ──────────────────────────────────────────────────────────────

HTML_PAGE = r"""<!DOCTYPE html>
<html lang="tr">
<head>
<meta charset="UTF-8">
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<link rel="icon" type="image/x-icon" href="/assets/moonstar.ico">
<link rel="shortcut icon" type="image/x-icon" href="/assets/moonstar.ico">
<title>MoonStar Türkçe Dil Kılavuzu</title>
<style>
* { margin: 0; padding: 0; box-sizing: border-box; }
label { font-weight: 600; }

/* Win16 Classic Theme */
body {
  font-family: 'MS Sans Serif', 'Microsoft Sans Serif', 'Segoe UI', 'Helvetica Neue', Arial, sans-serif;
  font-size: 14px;
  background: #008080;
  color: #000;
  overflow: hidden;
  height: 100vh;
}

/* Desktop */
.desktop {
  position: fixed;
  top: 0;
  left: 0;
  right: 0;
  bottom: 0;
  background: #008080;
  overflow: hidden;
}

/* Main application window */
.main-win {
  width: 100% !important;
  height: 100% !important;
  display: flex;
  flex-direction: column;
  min-width: 640px;
  min-height: 480px;
  overflow: hidden;
  box-sizing: border-box;
  background: #008080;
  border: none;
}
.main-win > .win-body {
  display: flex;
  flex-direction: column;
  flex: 1;
  min-height: 0;
  padding: 0 !important;
  overflow: hidden;
}

/* Menu Bar */
.menu-bar {
  flex-shrink: 0;
  background: #c0c0c0;
  padding: 1px 2px;
  display: flex;
  gap: 0;
  border-bottom: 1px solid #808080;
}
.menu-bar .menu-item {
  padding: 3px 8px;
  cursor: pointer;
  font-size: 13px;
  font-weight: 600;
  user-select: none;
}
.menu-bar .menu-item:hover {
  border-color: #fff #808080 #808080 #fff;
}
.menu-bar .menu-item.open {
  background: #000080;
  color: #fff;
  border-color: #808080 #fff #fff #808080;
}

/* Main work area — Win95 desktop surface */
.work-area {
  flex: 1 1 0;
  min-height: 0;
  overflow: hidden;
  position: relative;
  background: #008080;
}

/* Win16-style window frame */
.win-window {
  background: #c0c0c0;
  border: 2px solid;
  border-color: #fff #404040 #404040 #fff;
  box-shadow: 2px 2px 0 rgba(0,0,0,0.4);
  display: flex;
  flex-direction: column;
  min-width: 280px;
  box-sizing: border-box;
  position: absolute;
  left: 50%;
  top: 50%;
  transform: translate(-50%, -50%);
  z-index: 1;
}
.win-title {
  flex-shrink: 0;
  background: #000080;
  color: #fff;
  padding: 4px 6px;
  font-size: 14px;
  font-weight: 700;
  display: flex;
  align-items: center;
  gap: 4px;
  cursor: default;
}
.win-title.inactive {
  background: #808080;
}
.win-title-text { flex: 1; }
.win-title-icon {
  width: 16px;
  height: 16px;
  display: block;
  flex-shrink: 0;
  object-fit: contain;
  background: url('/assets/moonstar_icon.png?v=2') center / 16px 16px no-repeat;
  image-rendering: pixelated;
  image-rendering: crisp-edges;
}
.win-title-btns { display: flex; gap: 2px; margin-left: auto; }
.win-title-btns button {
  width: 18px; height: 16px;
  background: #c0c0c0;
  border: 2px solid;
  border-color: #fff #808080 #808080 #fff;
  font-size: 9px;
  font-weight: bold;
  line-height: 1;
  cursor: pointer;
  display: flex; align-items: center; justify-content: center;
  padding: 0;
}
.win-title-btns button:active {
  border-color: #808080 #fff #fff #808080;
}
.win-body {
  padding: 6px;
  font-size: 14px;
}
.win-status {
  background: #c0c0c0;
  border-top: 1px solid #808080;
  padding: 3px 6px;
  font-size: 13px;
  color: #444;
}

/* Win16-style buttons */
.win-btn {
  background: #c0c0c0;
  border: 2px solid;
  border-color: #fff #808080 #808080 #fff;
  padding: 3px 16px;
  font-size: 13px;
  font-family: inherit;
  cursor: pointer;
  outline: none;
  min-width: 60px;
}
.win-btn:active {
  border-color: #808080 #fff #fff #808080;
}
.win-btn.primary {
  font-weight: 700;
}
.win-btn.small {
  padding: 5px 12px;
  font-size: 14px;
  min-width: auto;
}

/* Win16-style input */
.win-input {
  border: 2px solid;
  border-color: #808080 #fff #fff #808080;
  padding: 5px 6px;
  font-size: 14px;
  font-family: inherit;
  outline: none;
  background: #fff;
}
.win-input:focus {
  border-color: #000;
}

/* Win16 listbox */
.win-list {
  border: 2px solid;
  border-color: #808080 #fff #fff #808080;
  background: #fff;
  overflow-y: auto;
  position: relative;
}

/* Dictionary split pane */
.dict-word {
  padding: 3px 6px;
  cursor: pointer;
  border-bottom: 1px dotted #ddd;
  font-size: 14px;
}
.dict-word:hover { background: #e8e8ff; }

.dict-sel { background: #000080; color: #fff; }
.dict-sel:hover { background: #000080; }
.dict-meaning {
  padding: 4px 6px;
  border-bottom: 1px solid #ccc;
  cursor: pointer;
  font-size: 14px;
}
.dict-meaning:hover { background: #e8e8ff; }
.dict-meaning .row-num { display: inline-block; min-width: 24px; color: #888; }
.meaning-sel { background: #000080; color: #fff; }
.meaning-sel .row-num { color: #88aaff; }
.meaning-sel:hover { background: #000080; }

/* 3D group box */
.group-box {
  border: 2px solid;
  border-color: #808080 #fff #fff #808080;
  padding: 8px 4px 4px 4px;
  margin-top: 4px;
  position: relative;
}
.group-box legend {
  position: absolute;
  top: -9px;
  left: 8px;
  background: #c0c0c0;
  padding: 0 6px;
  font-size: 13px;
  font-weight: 700;
  white-space: nowrap;
}
.win-list table {
  width: 100%;
  border-collapse: collapse;
  font-size: 14px;
}
.win-list th {
  background: #c0c0c0;
  text-align: left;
  padding: 3px 6px;
  font-weight: 600;
  border-bottom: 1px solid #808080;
  white-space: nowrap;
}
.win-list td {
  padding: 2px 6px;
  border-bottom: 1px solid #e0e0e0;
  white-space: nowrap;
}
.win-list tr.sel td {
  background: #000080;
  color: #fff;
}
.win-list tr:hover td {
  background: #d0d0ff;
}

/* Tab strip (win16 common control) */
.tab-strip {
  display: flex;
  gap: 0;
  border-bottom: 1px solid #808080;
  margin-bottom: 4px;
}
.tab-strip a {
  padding: 3px 12px;
  border: 1px solid #808080;
  border-bottom: none;
  background: #c0c0c0;
  text-decoration: none;
  color: #000;
  font-size: 12px;
  cursor: pointer;
  margin-bottom: -1px;
}
.tab-strip a.active {
  background: #fff;
  border-bottom: 1px solid #fff;
  font-weight: bold;
}

/* Group box */
.group-box {
  border: 2px solid;
  border-color: #808080 #fff #fff #808080;
  padding: 12px 6px 6px;
  margin: 6px 0;
  position: relative;
}
.group-box legend {
  background: #c0c0c0;
  padding: 0 6px;
  position: absolute;
  top: -8px;
  left: 6px;
  font-size: 14px;
  font-weight: 700;
}

/* Win16 status bar */
.status-bar {
  flex-shrink: 0;
  background: #c0c0c0;
  border-top: 2px solid;
  border-color: #fff #808080 #808080 #fff;
  padding: 0 8px;
  display: flex;
  font-size: 13px;
  height: 24px;
  min-height: 24px;
  max-height: 24px;
  line-height: 24px;
  align-items: center;
  box-sizing: border-box;
}
.status-bar .status-sep {
  width: 2px;
  height: 14px;
  background: #808080;
  margin: 0 6px;
  border-left: 1px solid #fff;
}

/* Scrollbar-like areas */
.scroll-area {
  overflow-y: auto;
  max-height: 400px;
}

/* Welcome screen — matches EXE toolbar dialog (104×50 btns + 98×98 Acer banner) */
.welcome-body {
  padding: 10px;
  display: flex;
  flex-direction: column;
  align-items: stretch;
  gap: 0;
  background: #c0c0c0;
  box-sizing: border-box;
}
.welcome-panel {
  border: 2px solid;
  border-color: #fff #808080 #808080 #fff;
  background: #c0c0c0;
  padding: 8px;
  display: flex;
  flex-direction: column;
  gap: 8px;
  box-sizing: border-box;
}
.welcome-grid {
  display: grid;
  grid-template-columns: repeat(3, 104px);
  grid-template-rows: repeat(2, 50px);
  gap: 6px;
  justify-content: center;
  flex-shrink: 0;
  line-height: 0;
}
.welcome-btn {
  width: 104px;
  height: 50px;
  padding: 0;
  margin: 0;
  border: 0;
  background: transparent;
  cursor: pointer;
  display: block;
  line-height: 0;
  user-select: none;
  -webkit-user-drag: none;
  outline: none;
}
.welcome-btn:focus,
.welcome-btn:focus-visible {
  outline: none;
}
.welcome-btn img {
  width: 104px;
  height: 50px;
  display: block;
  image-rendering: pixelated;
  image-rendering: crisp-edges;
  pointer-events: none;
  -webkit-user-drag: none;
}
.welcome-sep {
  height: 2px;
  border-top: 1px solid #808080;
  border-bottom: 1px solid #fff;
  margin: 0 2px;
  flex-shrink: 0;
}
.welcome-banner {
  width: 328px;
  height: 102px;
  margin: 0 auto;
  border: 2px solid;
  border-color: #808080 #fff #fff #808080;
  background: #800000;
  display: flex;
  align-items: stretch;
  overflow: hidden;
  box-sizing: border-box;
  flex-shrink: 0;
}
.welcome-banner-logo {
  width: 98px;
  height: 98px;
  flex-shrink: 0;
  image-rendering: pixelated;
  image-rendering: crisp-edges;
  display: block;
}
.welcome-banner-brand {
  flex: 1;
  min-width: 0;
  height: 98px;
  display: flex;
  flex-direction: column;
  align-items: center;
  justify-content: center;
  padding: 8px 10px 6px;
  box-sizing: border-box;
  gap: 4px;
}
.welcome-banner-svg {
  width: 100%;
  height: 48px;
  display: block;
  object-fit: contain;
  object-position: center;
}
.welcome-banner-sub {
  margin: 0;
  padding: 0;
  color: #fff;
  font-family: 'Times New Roman', 'MS Serif', serif;
  font-size: 18px;
  font-style: italic;
  font-weight: 400;
  line-height: 1;
  white-space: nowrap;
  text-align: center;
  letter-spacing: 0;
}

/* Hangman — pixel sizes match EXE assets: 25 / 52×76 / 98 / 63×39 */
.hm-main {
  display: flex; flex-direction: column;
  width: 330px; padding: 6px 8px 6px; gap: 6px;
  background: #c0c0c0; box-sizing: border-box;
}
.hm-upper {
  display: flex; flex-direction: row; gap: 10px;
  align-items: flex-start;
}
.hm-left {
  display: flex; flex-direction: column; gap: 0;
  width: 57px; padding: 1px 2px 1px 1px; line-height: 0;
  border: 2px solid; border-color: #808080 #fff #fff #808080;
  background: #c0c0c0; box-sizing: border-box; flex-shrink: 0;
}
.hm-keyrow { display: flex; gap: 0; line-height: 0; }
.hm-key {
  width: 25px; height: 25px; padding: 0; margin: 0; border: 0;
  background: transparent; cursor: pointer; display: block;
  image-rendering: pixelated; image-rendering: crisp-edges;
}
.hm-key.used { cursor: default; opacity: 1; }
.hm-key.idle { cursor: default; }
.kbd-grid { display: grid; grid-template-columns: repeat(5,auto); gap: 4px; justify-content: center; }
.kbd-key { cursor: pointer; width: 25px; height: 25px; padding: 0; margin: 0; border: 0; background: transparent; image-rendering: pixelated; image-rendering: crisp-edges; }
.kbd-key:hover { filter: brightness(1.1); }
.hm-right {
  width: 250px; display: flex; flex-direction: column;
  gap: 6px; flex-shrink: 0;
}
.hm-brand {
  width: 250px;
  height: 86px;
  box-sizing: border-box;
  background: #800000;
  border: 2px solid;
  border-color: #808080 #fff #fff #808080;
  display: flex;
  flex-direction: column;
  align-items: center;
  justify-content: center;
  padding: 8px 10px 6px;
  gap: 4px;
  flex-shrink: 0;
  overflow: hidden;
}
.hm-brand-svg {
  width: 100%;
  height: 48px;
  display: block;
  object-fit: contain;
  object-position: center;
}
.hm-brand-sub {
  margin: 0;
  padding: 0;
  color: #fff;
  font-family: 'Times New Roman', 'MS Serif', serif;
  font-size: 18px;
  font-style: italic;
  font-weight: 400;
  line-height: 1;
  white-space: nowrap;
  text-align: center;
  letter-spacing: 0;
}
.hm-status {
  display: flex; flex-direction: column;
  gap: 0; flex-shrink: 0;
  width: 250px;
  margin-top: 8px;
}
.hm-status-row {
  display: flex; flex-direction: row;
  align-items: flex-start; gap: 10px;
  width: 100%;
}
.hm-gallows {
  width: 60px; height: 84px; box-sizing: border-box;
  margin-top: 4px;
  border: 2px solid; border-color: #808080 #fff #fff #808080;
  background: #c0c0c0; padding: 2px; line-height: 0; flex-shrink: 0;
  display: flex; align-items: center; justify-content: center;
}
.hm-gallows img {
  width: 52px; height: 76px; display: block;
  image-rendering: pixelated; image-rendering: crisp-edges;
}
.hm-scorecol {
  width: 98px;
  display: flex;
  flex-direction: column;
  gap: 4px;
  margin-left: auto;
}
.hm-scorelabel {
  height: 16px; line-height: 16px;
  font-size: 13px; font-weight: 700;
  font-family: 'MS Sans Serif', Tahoma, sans-serif;
  margin-left: 4px;
}
.hm-scorebox {
  width: 100%; box-sizing: border-box;
  border: 2px solid; border-color: #808080 #fff #fff #808080;
  background: #c0c0c0; padding: 12px 8px;
  font-size: 18px; font-weight: 700;
  font-family: 'MS Sans Serif', Tahoma, sans-serif;
  display: flex; align-items: center; justify-content: center;
}
.hm-ad {
  width: 98px; height: 98px; line-height: 0; flex-shrink: 0;
  align-self: flex-end;
}
.hm-ad img {
  width: 98px; height: 98px; display: block;
  image-rendering: pixelated; image-rendering: crisp-edges;
}
.hm-wordbox {
  width: 250px; min-height: 36px; box-sizing: border-box;
  border: 2px solid; border-color: #808080 #fff #fff #808080;
  background: #c0c0c0; padding: 8px 12px;
  font-size: 15px; font-weight: bold;
  letter-spacing: 5px;
  font-family: 'MS Sans Serif', 'Microsoft Sans Serif', Tahoma, sans-serif;
  display: flex; align-items: center; justify-content: center;
  white-space: nowrap; overflow: hidden; flex-shrink: 0;
}
.hm-result {
  width: 250px;
  height: 14px; line-height: 14px;
  font-size: 11px; font-weight: 700; text-align: center;
}
.hm-btns {
  display: flex; flex-direction: row; gap: 8px;
  line-height: 0; flex-shrink: 0;
  justify-content: center;
  width: 250px;
}
.hm-btn {
  width: 63px; height: 39px; padding: 0; margin: 0; border: 0;
  background: transparent; cursor: pointer; display: block;
  image-rendering: pixelated; image-rendering: crisp-edges;
}
.hm-btn:active { filter: brightness(0.92); }

/* Other */
.hidden { display: none; }
.loading { padding: 20px; text-align: center; color: #666; }
.pagination { display: flex; gap: 4px; align-items: center; justify-content: center; padding: 4px 0; font-size: 13px; }
.pagination button { background: #c0c0c0; border: 1px solid; border-color: #fff #808080 #808080 #fff; padding: 2px 10px; font-size: 13px; cursor: pointer; font-family: inherit; }
.pagination button:active { border-color: #808080 #fff #fff #808080; }
.pagination button:disabled { opacity: .5; cursor: default; }
.pagination span { padding: 0 4px; }
.flag { display: inline-block; padding: 0 4px; font-size: 10px; }
.flag-normal { color: #080; }
.flag-variant { color: #800; }

/* Quiz topic selection — Klavye Seçimi style: list left, buttons right */
.quiz-topic-panel {
  display: flex;
  flex-direction: row;
  gap: 10px;
  align-items: stretch;
  min-height: 0;
  height: 100%;
}
.quiz-topic-main {
  flex: 1;
  min-width: 0;
  min-height: 0;
  display: flex;
  flex-direction: column;
  gap: 4px;
}
.quiz-topic-prompt {
  font-size: 13px;
  font-weight: 700;
  line-height: 1.3;
  flex-shrink: 0;
}
.quiz-topic-list {
  flex: 1;
  min-height: 180px;
  max-height: 280px;
  overflow-y: auto;
  background: #fff;
  border: 2px solid;
  border-color: #808080 #fff #fff #808080;
  box-shadow: inset 1px 1px 0 #000;
  padding: 1px;
  outline: none;
}
.quiz-topic-row {
  padding: 1px 4px;
  font-size: 13px;
  line-height: 16px;
  cursor: default;
  white-space: nowrap;
  overflow: hidden;
  text-overflow: ellipsis;
}
.quiz-topic-row.selected {
  background: #000080;
  color: #fff;
}
.quiz-topic-actions {
  display: flex;
  flex-direction: column;
  gap: 6px;
  flex-shrink: 0;
  line-height: 0;
  padding-top: 18px;
}
.quiz-topic-btn {
  width: 63px;
  height: 39px;
  border: 0;
  padding: 0;
  margin: 0;
  background: transparent;
  cursor: pointer;
  image-rendering: pixelated;
  image-rendering: crisp-edges;
  display: block;
}
.quiz-topic-btn:active {
  filter: brightness(0.92);
}
#quizTopicDialog .win-window {
  width: 340px;
  height: auto;
  position: relative;
  top: auto;
  left: auto;
  transform: none;
}

/* Dropdown menu */
.dropdown {
  display: none;
  position: absolute;
  background: #c0c0c0;
  border: 2px solid;
  border-color: #fff #808080 #808080 #fff;
  z-index: 1000;
  padding: 2px;
  min-width: 180px;
  box-shadow: 2px 2px 0 rgba(0,0,0,0.3);
}
.dropdown.open { display: block; }
.dropdown-item {
  padding: 3px 20px;
  cursor: pointer;
  font-size: 13px;
  font-weight: 600;
  white-space: nowrap;
  border: 1px solid transparent;
}
.dropdown-item:hover {
  background: #000080;
  color: #fff;
  border-color: #fff #808080 #808080 #fff;
}
.dropdown-sep {
  border-top: 1px solid #808080;
  border-bottom: 1px solid #fff;
  margin: 2px 4px;
}

/* Dialog overlay */
.dialog-overlay {
  display: none;
  position: fixed;
  top: 0; left: 0; right: 0; bottom: 0;
  background: rgba(0,0,0,0.4);
  z-index: 500;
}
.dialog-overlay.open { display: flex; align-items: center; justify-content: center; }

/* Context help */
.help-text { font-size: 11px; color: #444; padding: 8px; }
</style>
</head>
<body>

<div class="desktop">
  <!-- Main Application Window -->
  <div class="main-win" id="mainWin">
    <div class="win-title"><img class="win-title-icon" src="/assets/moonstar_icon.png?v=2"><span class="win-title-text">MoonStar Türkçe Dil Kılavuzu</span></div>
    <div class="win-body" style="padding:0;">
      <!-- Menu Bar -->
      <div class="menu-bar" id="menuBar">
        <div class="menu-item" onclick="toggleMenu('fileMenu', event)">Dosya</div>
        <div class="menu-item" onclick="toggleMenu('editMenu', event)">Düzen</div>
        <div class="menu-item" onclick="toggleMenu('searchMenu', event)">Ara</div>
        <div class="menu-item" onclick="toggleMenu('checkMenu', event)">Denetim</div>
        <div class="menu-item" onclick="toggleMenu('dictMenu', event)">Sözlük</div>
        <div class="menu-item" onclick="toggleMenu('gameMenu', event)">Oyun</div>
        <div class="menu-item" onclick="toggleMenu('statsMenu', event)">İstatistik</div>
        <div class="menu-item" onclick="toggleMenu('optionsMenu', event)">Seçenekler</div>
        <div class="menu-item" onclick="toggleMenu('helpMenu', event)">Yardım</div>
      </div>

      <!-- Dropdown Menus -->
      <div class="dropdown" id="fileMenu">
        <div class="dropdown-item" onclick="winAlert('Bu özellik sadece veri görüntüleme amaçlıdır.')">&Yeni</div>
        <div class="dropdown-item" onclick="winAlert('Bu özellik sadece veri görüntüleme amaçlıdır.')">Dosya &Açma</div>
        <div class="dropdown-sep"></div>
        <div class="dropdown-item" onclick="winAlert('Bu özellik sadece veri görüntüleme amaçlıdır.')">Çıkış</div>
      </div>
      <div class="dropdown" id="editMenu">
        <div class="dropdown-item" onclick="winAlert('Bu özellik sadece veri görüntüleme amaçlıdır.')">Kopyala</div>
        <div class="dropdown-item" onclick="winAlert('Bu özellik sadece veri görüntüleme amaçlıdır.')">Yapıştır</div>
      </div>
      <div class="dropdown" id="searchMenu">
        <div class="dropdown-item" onclick="showFindDialog()">Al ve bul</div>
        <div class="dropdown-item" onclick="showReplaceDialog()">Değiştir</div>
      </div>
      <div class="dropdown" id="checkMenu">
        <div class="dropdown-item" onclick="showCheckOptions()">Denetim Opsiyonlar</div>
      </div>
      <div class="dropdown" id="dictMenu">
        <div class="dropdown-item" onclick="openWindow('ing-tr')">Leb demeden (İngilizce → Türkçe)</div>
        <div class="dropdown-item" onclick="openWindow('tr-ing')">Leb demeden (Türkçe → İngilizce)</div>
        <div class="dropdown-sep"></div>
        <div class="dropdown-item" onclick="openWindow('synonyms')">Eş Anlamlı kelimeler</div>
        <div class="dropdown-sep"></div>
        <div class="dropdown-item" onclick="openWindow('tr-tr')">Türkçe Leb Demeden</div>
      </div>
      <div class="dropdown" id="gameMenu">
        <div class="dropdown-item" onclick="openWindow('quiz')">Kelime Oyunu</div>
      </div>
      <div class="dropdown" id="statsMenu">
        <div class="dropdown-item" onclick="openStatsWindow()">Metin İstatistik</div>
      </div>
      <div class="dropdown" id="optionsMenu">
        <div class="dropdown-item" onclick="winAlert('Bu özellik sadece veri görüntüleme amaçlıdır.')">Karakter Listesi</div>
        <div class="dropdown-item" onclick="showKeyboardModule()">Klavye Seçimi</div>
        <div class="dropdown-item" onclick="winAlert('Bu özellik sadece veri görüntüleme amaçlıdır.')">Genel tanımlar</div>
      </div>
      <div class="dropdown" id="helpMenu">
        <div class="dropdown-item" onclick="showAbout()">MoonStar Hakkında</div>
      </div>

      <!-- Client Area for Child Windows -->
      <div class="work-area" id="workArea" style="flex:1 1 0;min-height:0;">
        <!-- Windows will be added here dynamically -->
      </div>
    </div>

    <!-- Status Bar -->
    <div class="status-bar">
      <span>MoonStar Veri Gezgini</span>
      <span class="status-sep"></span>
      <span id="statusText">TRK: 17.975 | TUR: 26.775 | SYN: 10.640 | REV: 37.043 | KELİME OYUNU: 12.437</span>
    </div>
  </div>
</div>

<!-- About Dialog -->
<div class="dialog-overlay" id="aboutDialog">
  <div class="win-window" style="min-width:350px;">
    <div class="win-title inactive"><img class="win-title-icon" src="/assets/moonstar_icon.png?v=2"><span class="win-title-text">MoonStar Hakkında</span>
      <div class="win-title-btns"><button onclick="closeDialog('aboutDialog')">✕</button></div>
    </div>
    <div class="win-body" style="text-align:center;padding:20px;">
      <div style="font-size:36px;color:#000080;margin-bottom:8px;">★</div>
      <div style="font-size:16px;font-weight:bold;">MoonStar</div>
      <div style="font-size:14px;margin:4px 0;">Türkçe Dil Kılavuzu</div>
      <div style="font-size:13px;color:#666;margin:12px 0;">
        Veri Gezgini Sürümü<br>
        Tersine Mühendislik: yasinkuyu<br>
        2026
      </div>
      <div style="font-size:13px;color:#888;">
        TRK: 17.975 | TUR: 26.775 | SYN: 10.640 | REV: 37.043 | QUIZ: 12.437
      </div>
      <div style="margin-top:16px;">
        <button class="win-btn" onclick="closeDialog('aboutDialog')">Tamam</button>
      </div>
    </div>
  </div>
</div>

<!-- Find Dialog -->
<div class="dialog-overlay" id="findDialog">
  <div class="win-window" style="min-width:350px;">
    <div class="win-title inactive"><img class="win-title-icon" src="/assets/moonstar_icon.png?v=2"><span class="win-title-text">Al ve bul</span>
      <div class="win-title-btns"><button onclick="closeDialog('findDialog')">✕</button></div>
    </div>
    <div class="win-body" style="padding:12px;">
      <div style="margin-bottom:8px;">
        <label>Bulunacak:</label><br>
        <input class="win-input" type="text" id="findInput" style="width:100%;" onkeyup="if(event.key==='Enter') doFind()">
      </div>
      <div style="margin-bottom:8px;">
        <label>Bulma tipleri:</label><br>
        <label><input type="radio" name="findType" checked onclick="document.getElementById('findInput').placeholder='Kelime girin...'"> Tüm sözlükler</label><br>
        <label><input type="radio" name="findType" onclick="document.getElementById('findInput').placeholder='İngilizce kelime girin...'"> İngilizce → Türkçe</label><br>
        <label><input type="radio" name="findType" onclick="document.getElementById('findInput').placeholder='Türkçe kelime girin...'"> Türkçe → Türkçe</label><br>
        <label><input type="radio" name="findType" onclick="document.getElementById('findInput').placeholder='Konu veya kelime...'"> Adam Asma</label>
      </div>
      <div style="margin-top:8px;text-align:right;">
        <button class="win-btn primary" onclick="doFind()">Bul</button>
        <button class="win-btn" onclick="closeDialog('findDialog')">İptal</button>
      </div>
      <div id="findResults" style="margin-top:8px;max-height:200px;overflow-y:auto;font-size:13px;"></div>
    </div>
  </div>
</div>

<!-- Kelime Oyunu topic picker (EXE-style listbox + Tamam/İptal) -->
<div class="dialog-overlay" id="quizTopicDialog">
  <div class="win-window">
    <div class="win-title inactive"><img class="win-title-icon" src="/assets/moonstar_icon.png?v=2"><span class="win-title-text">Kelime Oyunu</span>
      <div class="win-title-btns"><button onclick="closeQuizTopicDialog()">✕</button></div>
    </div>
    <div class="win-body" style="padding:8px;height:320px;">
      <div class="quiz-topic-panel">
        <div class="quiz-topic-main">
          <div class="quiz-topic-prompt">Kelime Oyunu oynamak için bir konu seçin.</div>
          <div class="quiz-topic-list" id="quizTopicList" tabindex="0"
               onkeydown="quizTopicKeydown(event)"></div>
        </div>
        <div class="quiz-topic-actions">
          <img class="quiz-topic-btn" width="63" height="39" src="/assets/btn_tamam.png" alt="Tamam" title="Tamam" onclick="confirmQuizTopic()">
          <img class="quiz-topic-btn" width="63" height="39" src="/assets/btn_iptal.png" alt="İptal" title="İptal" onclick="closeQuizTopicDialog()">
        </div>
      </div>
    </div>
  </div>
</div>

<script>
// ─── State ────────────────────────────────────────────────────────────────
let state = {
  windows: {},
  nextWindowId: 0,
  pageCache: {},
};

// ─── Win16 Alert Dialog ──────────────────────────────────────────────────
function winAlert(msg) {
  const id = 'alert-' + Date.now();
  const ov = document.createElement('div');
  ov.className = 'dialog-overlay open';
  ov.id = id;
  ov.innerHTML = `<div class="win-window" style="min-width:300px;max-width:400px;">
    <div class="win-title inactive"><img class="win-title-icon" src="/assets/moonstar_icon.png?v=2"><span class="win-title-text">MoonStar</span>
      <div class="win-title-btns"><button onclick="document.getElementById('${id}').remove()">✕</button></div>
    </div>
    <div class="win-body" style="padding:20px;text-align:center;">
      <div style="font-size:14px;margin-bottom:16px;">${msg}</div>
      <button class="win-btn" onclick="document.getElementById('${id}').remove()">Tamam</button>
    </div>
  </div>`;
  document.body.appendChild(ov);
}

// ─── Menu System ──────────────────────────────────────────────────────────
function closeAllMenus() {
  document.querySelectorAll('.dropdown').forEach(m => m.classList.remove('open'));
  document.querySelectorAll('.menu-item').forEach(m => m.classList.remove('open'));
}

function toggleMenu(id, event) {
  event.stopPropagation();
  const menu = document.getElementById(id);
  const isOpen = menu.classList.contains('open');
  closeAllMenus();
  if (!isOpen) {
    menu.classList.add('open');
    event.target.classList.add('open');
    // Position menu below menu item
    const rect = event.target.getBoundingClientRect();
    menu.style.left = rect.left + 'px';
    menu.style.top = (rect.bottom + 1) + 'px';
  }
}

document.addEventListener('click', function(e) {
  if (!e.target.closest('.menu-item') && !e.target.closest('.dropdown')) {
    closeAllMenus();
  }
});

// ─── Windows System ──────────────────────────────────────────────────────
function closeAllWindows() {
  closeQuizTopicDialog();
  Object.keys(state.windows).forEach(k => {
    const el = document.getElementById(k);
    if (el) el.remove();
    delete state.windows[k];
  });
}

function openWindow(type, opts) {
  opts = opts || {};
  closeAllMenus();
  if (type === 'quiz') {
    openHangman();
    return;
  }
  if (!opts.keep) closeAllWindows();
  const id = 'win-' + (state.nextWindowId++);
  const workArea = document.getElementById('workArea');
  
  let config = { title: 'Pencere', content: '<div class="loading">Yükleniyor...</div>', width: 'auto', height: 'auto' };
  
  switch(type) {
    case 'ing-tr':
      config = { title: 'İngilizce Türkçe Sözlük', type: 'trk', w: 560, h: 380 };
      break;
    case 'tr-ing':
      config = { title: 'Türkçe İngilizce Sözlük', type: 'rev', w: 560, h: 380 };
      break;
    case 'synonyms':
      config = { title: 'Türkçe Eş Anlamlı Sözcükler', type: 'syn', w: 600, h: 420 };
      break;
    case 'tr-tr':
      config = { title: 'Türkçe Leb Demeden', type: 'tur', w: 480, h: 380 };
      break;
    case 'stats':
      config = { title: 'Metin İstatistik', type: 'stats', w: 480, h: 340 };
      break;
    default:
      config = { title: 'Pencere', type: 'trk', w: 400, h: 300 };
  }

  let html = `<div class="win-window" id="${id}" style="width:${config.w}px;height:${config.h}px;${opts.keep ? 'top:36px;left:48px;transform:none;' : ''}">`;
  html += `<div class="win-title"><img class="win-title-icon" src="/assets/moonstar_icon.png?v=2"><span class="win-title-text">${config.title}</span>`;
  html += `<div class="win-title-btns"><button onclick="closeWindow('${id}')">✕</button></div></div>`;
  
  if (config.type === 'trk' || config.type === 'rev') {
    html += `<div class="win-body" style="padding:4px;flex:1;display:flex;flex-direction:column;min-height:0;">
      <div style="margin-bottom:4px;display:flex;gap:4px;flex-shrink:0;">
        <input class="win-input" type="text" placeholder="Sözcük ara..." style="flex:1;" id="${id}-search" oninput="dictSearchDebounced('${id}')">
        <button class="win-btn small" onclick="dictSearch('${id}')">👌 Tamam</button>
      </div>
      <div style="display:flex;gap:4px;margin-bottom:4px;flex:1;min-height:0;">
        <div class="group-box" style="flex:1;display:flex;flex-direction:column;"><legend>${config.type==='trk'?'İngilizce Sözcükler':'Türkçe Sözcükler'}</legend>
          <div class="win-list" style="flex:1;overflow-y:auto;" id="${id}-list"></div>
        </div>
        <div class="group-box" style="flex:1;display:flex;flex-direction:column;"><legend>${config.type==='trk'?'Türkçe Karşılıklar':'İngilizce Karşılıklar'}</legend>
          <div class="win-list" style="flex:1;overflow-y:auto;" id="${id}-defn"></div>
        </div>
      </div>
      <div style="flex-shrink:0;margin-bottom:4px;">
        <label style="font-weight:700;font-size:14px;">${config.type==='trk'?'Türkçe Karşılık':'İngilizce Karşılık'}</label><br>
        <input class="win-input" type="text" readonly style="width:100%;background:#fff;color:#000;border:2px inset #c0c0c0;" id="${id}-detail">
      </div>
      <div class="win-status" id="${id}-status" style="flex-shrink:0;"></div>
    </div>`;
  } else if (config.type === 'syn') {
    html += `<div class="win-body" style="padding:4px;flex:1;display:flex;flex-direction:column;min-height:0;">
      <div style="display:flex;gap:4px;flex:1;min-height:0;margin-bottom:4px;">
        <div style="flex:1;display:flex;flex-direction:column;gap:4px;min-height:0;">
          <div class="group-box" style="flex-shrink:0;"><legend>Sözcük</legend>
            <div style="display:flex;gap:4px;">
              <input class="win-input" type="text" style="flex:1;" id="${id}-search" placeholder="" oninput="dictSearchDebounced('${id}')">
              <button class="win-btn small" onclick="dictSearch('${id}')">Tamam</button>
            </div>
          </div>
          <div class="group-box" style="flex:1;display:flex;flex-direction:column;min-height:0;"><legend>Kök Sözcük</legend>
            <div class="win-list" style="flex:1;overflow-y:auto;" id="${id}-list"></div>
          </div>
          <div class="group-box" style="flex:1;display:flex;flex-direction:column;min-height:0;"><legend>Anlam Grupları</legend>
            <div class="win-list" style="flex:1;overflow-y:auto;" id="${id}-groups"></div>
          </div>
        </div>
        <div class="group-box" style="flex:1;display:flex;flex-direction:column;"><legend>Eş Anlamları</legend>
          <div class="win-list" style="flex:1;overflow-y:auto;" id="${id}-defn"></div>
        </div>
      </div>
      <div style="text-align:right;flex-shrink:0;padding:2px 0;display:flex;gap:4px;justify-content:flex-end;">
        <button class="win-btn primary" onclick="dictSearch('${id}')">Tamam</button>
        <button class="win-btn" onclick="closeWindow('${id}')">İptal</button>
      </div>
      <div class="win-status" id="${id}-status" style="flex-shrink:0;"></div>
    </div>`;
  } else if (config.type === 'tur') {
    html += `<div class="win-body" style="padding:4px;flex:1;display:flex;flex-direction:column;min-height:0;">
      <div style="margin-bottom:4px;flex-shrink:0;">
        <input class="win-input" type="text" placeholder="Sözcük ara..." style="width:100%;" id="${id}-search" oninput="dictSearchDebounced('${id}')">
      </div>
      <div class="group-box" style="flex:1;display:flex;flex-direction:column;margin-bottom:4px;"><legend>Türkçe Sözcükler</legend>
        <div class="win-list" style="flex:1;overflow-y:auto;" id="${id}-list"></div>
      </div>
      <div class="win-status" id="${id}-status" style="flex-shrink:0;"></div>
    </div>`;
  } else if (config.type === 'stats') {
    html += `<div class="win-body" id="${id}-body" style="padding:4px;flex:1;display:flex;flex-direction:column;min-height:0;overflow:auto;"><div class="loading">Yükleniyor...</div></div>`;
  }
  
  html += `</div>`;
  
  // Insert at beginning of work area
  workArea.insertAdjacentHTML('afterbegin', html);
  
  // Load data
  state.windows[id] = { type: config.type, id: id };
  
  switch(config.type) {
    case 'trk': loadWindowDict(id, 'trk', '/api/trk'); break;
    case 'rev': loadWindowDict(id, 'rev', '/api/rev'); break;
    case 'syn': loadWindowDict(id, 'syn', '/api/syn'); break;
    case 'tur': loadWindowDict(id, 'tur', '/api/tur'); break;
    case 'stats': loadWindowStats(id); break;
  }
}

function closeWindow(id) {
  const win = document.getElementById(id);
  if (win) win.remove();
  delete state.windows[id];
  if (state.activeHangmanId === id) state.activeHangmanId = null;
  if (Object.keys(state.windows).length === 0) {
    showWelcomeWindow();
  }
}

// ─── Synonyms List Render ────────────────────────────────────────────────
function renderSynonyms(winId, synonyms) {
  const parts = synonyms.split(' | ').filter(Boolean);
  const df = document.getElementById(winId + '-defn');
  if (!df) return;
  if (!parts.length) {
    df.innerHTML = '<div style="color:#888;padding:8px;">Eş anlamlı yok</div>';
    return;
  }
  df.innerHTML = parts.map((m, i) =>
    `<div class="dict-word${i===0?' dict-sel':''}" onclick="synonymSelect('${winId}',${i})">${m}</div>`
  ).join('');
}
function synonymSelect(winId, idx) {
  document.querySelectorAll(`#${winId}-defn .dict-word`).forEach(el => el.classList.remove('dict-sel'));
  const items = document.querySelectorAll(`#${winId}-defn .dict-word`);
  if (items[idx]) items[idx].classList.add('dict-sel');
}

// ─── Dictionary Window ───────────────────────────────────────────────────
// ─── Dictionary Window ───────────────────────────────────────────────────
function loadWindowDict(winId, type, apiUrl) {
  const key1 = { trk: 'en', rev: 'tr', syn: 'word', tur: 'word' }[type];
  const key2 = { trk: 'tr', rev: 'en', syn: 'synonyms' }[type];
  
  fetch(apiUrl + `?page=1&per_page=99999`)
    .then(r=>r.json())
    .then(d=>{
      state.windowData = state.windowData || {};
      state.windowData[winId] = d.data;
      state.activeData = state.activeData || {};
      state.activeData[winId] = []; // Start empty
      
      const listEl = document.getElementById(winId + '-list');
      if (listEl) {
        listEl.innerHTML = ''; // Start empty
      }
      const defnEl = document.getElementById(winId + '-defn');
      if (defnEl) {
        defnEl.innerHTML = ''; // Start empty
      }
      const dt = document.getElementById(winId + '-detail');
      if (dt) {
        dt.value = ''; // Start empty
      }
      document.getElementById(winId + '-status').textContent = `${d.total.toLocaleString()} kayıt`;
    });
}

function renderMeanings(winId, meanings) {
  const parts = meanings.replace(/^#/, '').split('|').map(s => s.replace(/^#/, '').trim()).filter(Boolean);
  const df = document.getElementById(winId + '-defn');
  if (!df) return;
  if (!parts.length) {
    df.innerHTML = '<div style="color:#888;padding:8px;">Anlam yok</div>';
    return;
  }
  _meaningWin = _meaningWin || {};
  _meaningWin[winId] = { parts: parts, sel: 0 };
  df.innerHTML = parts.map((m, i) => {
    let numText = '';
    let content = m;
    let match = m.match(/^(\d+)\.(.*)/s);
    if (match) {
      numText = match[1] + '.';
      content = match[2];
    } else {
      numText = i === 0 ? '1.' : '';
    }
    // Render newlines as indented breaks
    content = content.replace(/\n/g, '<br>&nbsp;&nbsp;');
    return `<div class="dict-meaning${i===0?' meaning-sel':''}" onclick="selectMeaning('${winId}',${i})"><span class="row-num">${numText}</span> ${content}</div>`;
  }).join('');
  const dt = document.getElementById(winId + '-detail');
  if (dt) {
    dt.value = parts[0].replace(/^\d+\.\s*/, '').replace(/\n\s*/g, ', ');
  }
}

let _meaningWin = {};
function selectMeaning(winId, idx) {
  const mw = _meaningWin[winId];
  if (!mw || !mw.parts[idx]) return;
  mw.sel = idx;
  document.querySelectorAll(`#${winId}-defn .dict-meaning`).forEach(el => el.classList.remove('meaning-sel'));
  const items = document.querySelectorAll(`#${winId}-defn .dict-meaning`);
  if (items[idx]) items[idx].classList.add('meaning-sel');
  const dt = document.getElementById(winId + '-detail');
  if (dt) {
    dt.value = mw.parts[idx].replace(/^\d+\.\s*/, '').replace(/\n\s*/g, ', ');
  }
}

function dictSelect(winId, key2, idx) {
  const isSyn = key2 === 'synonyms';
  document.querySelectorAll(`#${winId}-list .dict-word`).forEach(el => el.classList.remove('dict-sel'));
  const items = document.querySelectorAll(`#${winId}-list .dict-word`);
  if (items[idx]) items[idx].classList.add('dict-sel');
  
  const wd = (state.activeData && state.activeData[winId]) || (state.windowData && state.windowData[winId]);
  if (wd && wd[idx]) {
    const val = wd[idx][key2] || '';
    if (isSyn) {
      renderSynonyms(winId, val);
    } else {
      renderMeanings(winId, val);
    }
  }
  // Anlam Grupları: fill with English meaning groups from entry's 'groups' field
  const grp = document.getElementById(winId + '-groups');
  if (grp && wd && wd[idx]) {
    const groups = wd[idx]['groups'] || '';
    if (groups) {
      const parts = groups.split(' | ').filter(Boolean);
      grp.innerHTML = parts.map(g =>
        `<div class="dict-meaning">${g}</div>`
      ).join('') || '<div style="color:#888;padding:8px;">Grup yok</div>';
    } else {
      grp.innerHTML = '<div style="color:#888;padding:8px;">Grup yok</div>';
    }
  }
}

function normalizeSearch(s) {
  return s.toLowerCase().replace(/ı/g,'i').replace(/ş/g,'s').replace(/ç/g,'c').replace(/ö/g,'o').replace(/ü/g,'u').replace(/ğ/g,'g');
}
function dictSearch(winId) {
  const input = document.getElementById(winId + '-search');
  const q = input ? input.value.trim() : '';
  const win = state.windows[winId];
  if (!win) return;
  
  const key1 = { trk: 'en', rev: 'tr', syn: 'word', tur: 'word' }[win.type];
  const key2 = { trk: 'tr', rev: 'en', syn: 'synonyms' }[win.type];
  const fullData = state.windowData && state.windowData[winId];
  if (!fullData || !fullData.length) return;
  
  state.activeData = state.activeData || {};
  
  if (!q) {
    state.activeData[winId] = [];
    document.getElementById(winId + '-list').innerHTML = '';
    const defnEl = document.getElementById(winId + '-defn');
    if (defnEl) defnEl.innerHTML = '';
    const dt = document.getElementById(winId + '-detail');
    if (dt) dt.value = '';
    return;
  }
  
  const qn = normalizeSearch(q);
  const filtered = fullData.filter(e => normalizeSearch(e[key1] || '').startsWith(qn));
  state.activeData[winId] = filtered;
  
  const listEl = document.getElementById(winId + '-list');
  if (filtered.length === 0) {
    if (listEl) listEl.innerHTML = '<div style="color:#888;padding:8px;">Sonuç bulunamadı</div>';
    const defnEl = document.getElementById(winId + '-defn');
    if (defnEl) defnEl.innerHTML = '';
    const dt = document.getElementById(winId + '-detail');
    if (dt) dt.value = '';
    return;
  }
  
  let listHtml = filtered.map((e, i) => {
    let en = e[key1] || '';
    return `<div class="dict-word${i===0?' dict-sel':''}" onclick="dictSelect('${winId}','${key2||''}',${i})">${en}</div>`;
  }).join('');
  
  if (listEl) {
    listEl.innerHTML = listHtml;
    listEl.scrollTop = 0;
  }
  
  dictSelect(winId, key2, 0);
}

let _searchTimer = {};
function dictSearchDebounced(winId) {
  clearTimeout(_searchTimer[winId]);
  _searchTimer[winId] = setTimeout(() => dictSearch(winId), 150);
}

// ─── Quiz Topics Dialog (EXE listbox: select → Tamam / İptal) ─────────────
let quizTopicState = { topics: [], selected: null, hostId: null, typePrefix: '', lastTopicIdx: null };

function escHtml(s) {
  return String(s).replace(/&/g,'&amp;').replace(/</g,'&lt;').replace(/>/g,'&gt;').replace(/"/g,'&quot;');
}

function showQuizTopicDialog(hostId) {
  quizTopicState.hostId = hostId;
  const dlg = document.getElementById('quizTopicDialog');
  const list = document.getElementById('quizTopicList');
  list.innerHTML = '<div style="padding:8px;color:#666;">Yükleniyor...</div>';
  dlg.classList.add('open');

  fetch('/api/quiz/topics').then(r=>r.json()).then(d=>{
    const topics = d.topics || [];
    quizTopicState.topics = topics;
    const prevIdx = quizTopicState.lastTopicIdx;
    const hasPrev = prevIdx != null && topics.some(t => t.idx === prevIdx);
    quizTopicState.selected = hasPrev ? prevIdx : (topics.length ? topics[0].idx : null);
    quizTopicState.typePrefix = '';
    list.innerHTML = '';
    topics.forEach((t, i) => {
      const row = document.createElement('div');
      const sel = t.idx === quizTopicState.selected;
      row.className = 'quiz-topic-row' + (sel ? ' selected' : '');
      row.dataset.idx = String(t.idx);
      row.dataset.name = t.name;
      row.textContent = t.name;
      row.onclick = () => selectQuizTopic(t.idx);
      row.ondblclick = () => confirmQuizTopic();
      list.appendChild(row);
    });
    list.focus();
  });
}

function closeQuizTopicDialog() {
  document.getElementById('quizTopicDialog').classList.remove('open');
  quizTopicState.typePrefix = '';
}

function selectQuizTopic(idx) {
  quizTopicState.selected = idx;
  const list = document.getElementById('quizTopicList');
  list.querySelectorAll('.quiz-topic-row').forEach(row => {
    const on = Number(row.dataset.idx) === idx;
    row.classList.toggle('selected', on);
    if (on) row.scrollIntoView({ block: 'nearest' });
  });
}

function confirmQuizTopic() {
  const hostId = quizTopicState.hostId;
  const idx = quizTopicState.selected;
  if (idx == null || !hostId) return;
  quizTopicState.lastTopicIdx = idx;
  const topic = (quizTopicState.topics || []).find(t => t.idx === idx);
  closeQuizTopicDialog();
  startHangmanRound(hostId, idx, topic ? topic.name : '');
}

function quizTopicKeydown(ev) {
  const topics = quizTopicState.topics || [];
  if (!topics.length) return;
  let i = topics.findIndex(t => t.idx === quizTopicState.selected);
  if (i < 0) i = 0;

  if (ev.key === 'ArrowDown') {
    ev.preventDefault();
    selectQuizTopic(topics[Math.min(i + 1, topics.length - 1)].idx);
  } else if (ev.key === 'ArrowUp') {
    ev.preventDefault();
    selectQuizTopic(topics[Math.max(i - 1, 0)].idx);
  } else if (ev.key === 'Home') {
    ev.preventDefault();
    selectQuizTopic(topics[0].idx);
  } else if (ev.key === 'End') {
    ev.preventDefault();
    selectQuizTopic(topics[topics.length - 1].idx);
  } else if (ev.key === 'PageDown') {
    ev.preventDefault();
    selectQuizTopic(topics[Math.min(i + 10, topics.length - 1)].idx);
  } else if (ev.key === 'PageUp') {
    ev.preventDefault();
    selectQuizTopic(topics[Math.max(i - 10, 0)].idx);
  } else if (ev.key === 'Enter') {
    ev.preventDefault();
    confirmQuizTopic();
  } else if (ev.key === 'Escape') {
    ev.preventDefault();
    closeQuizTopicDialog();
  } else if (ev.key.length === 1 && !ev.ctrlKey && !ev.metaKey && !ev.altKey) {
    // Win16 listbox type-ahead
    ev.preventDefault();
    const now = Date.now();
    if (!quizTopicState._typeAt || now - quizTopicState._typeAt > 900) {
      quizTopicState.typePrefix = '';
    }
    quizTopicState._typeAt = now;
    quizTopicState.typePrefix += ev.key;
    const qn = normalizeSearch(quizTopicState.typePrefix);
    const hit = topics.find(t => normalizeSearch(t.name).startsWith(qn));
    if (hit) selectQuizTopic(hit.idx);
  }
}

// ─── Hangman (Kelime Oyunu) ─────────────────────────────────────────────
// Original EXE: left col A…L, right col M…Z then ?
const HM_LETTERS = 'ABCÇDEFGĞHIİJKLMNOÖPRSŞTUÜVYZ?';
const HM_KEYS = [
  ['A', 'M'], ['B', 'N'], ['C', 'O'], ['Ç', 'Ö'], ['D', 'P'],
  ['E', 'R'], ['F', 'S'], ['G', 'Ş'], ['Ğ', 'T'], ['H', 'U'],
  ['I', 'Ü'], ['İ', 'V'], ['J', 'Y'], ['K', 'Z'], ['L', '?'],
];
const HM_START_SCORE = 10000;

function hmKeyIndex(letter) {
  return HM_LETTERS.indexOf(letter);
}

function openHangman() {
  closeAllWindows();
  closeQuizTopicDialog();
  const id = 'win-hm-' + (state.nextWindowId++);
  const workArea = document.getElementById('workArea');

  let html = `<div class="win-window" id="${id}" style="width:360px;height:auto;top:10px;transform:translateX(-50%);">`;
  html += `<div class="win-title"><img class="win-title-icon" src="/assets/moonstar_icon.png?v=2"><span class="win-title-text">Kelime Oyunu</span>`;
  html += `<div class="win-title-btns"><button onclick="closeWindow('${id}')">✕</button></div></div>`;
  html += `<div class="win-body" style="padding:0;display:block;background:#c0c0c0;">`;
  html += `<div class="hm-main" id="${id}-game"></div>`;
  html += `</div></div>`;

  workArea.insertAdjacentHTML('afterbegin', html);
  state.windows[id] = {
    type: 'hangman', id: id, topicIdx: null, topicName: '',
    hangman: {
      word: '', hint: '', topicIdx: null,
      guessed: [], wrong: 0, maxWrong: 9, done: false, id: id,
      score: HM_START_SCORE, started: false
    }
  };
  state.activeHangmanId = id;
  renderHangman(id);
}

function hangmanBasla(id) {
  // EXE: Başla opens topic / word-source dialog, then starts a round
  showQuizTopicDialog(id);
}

function hangmanSozluk(id) {
  // Keep hangman open; dictionary is a sibling window like Win16 MDI
  state.activeHangmanId = id;
  openWindow('ing-tr', { keep: true });
}

function toTrUpper(s) {
  return String(s || '')
    .replace(/i/g, 'İ')
    .replace(/ı/g, 'I')
    .toLocaleUpperCase('tr-TR');
}

function hangmanKeyFromEvent(ev) {
  if (ev.key === '?' || (ev.key === '/' && ev.shiftKey)) return '?';
  if (ev.key.length !== 1 || ev.ctrlKey || ev.metaKey || ev.altKey) return null;
  // Preserve dotted / dotless I distinction from the physical key
  if (ev.key === 'i') return 'İ';
  if (ev.key === 'ı') return 'I';
  if (ev.key === 'I') return 'I';
  if (ev.key === 'İ') return 'İ';
  const up = toTrUpper(ev.key);
  return HM_LETTERS.includes(up) ? up : null;
}

function activeHangmanId() {
  if (state.activeHangmanId && state.windows[state.activeHangmanId]) {
    return state.activeHangmanId;
  }
  for (const id of Object.keys(state.windows)) {
    if (state.windows[id].type === 'hangman') return id;
  }
  return null;
}

document.addEventListener('keydown', function(ev) {
  if (document.getElementById('quizTopicDialog')?.classList.contains('open')) return;
  if (document.querySelector('.dialog-overlay.open')) return;
  const tag = (ev.target && ev.target.tagName) || '';
  if (tag === 'INPUT' || tag === 'TEXTAREA' || ev.target?.isContentEditable) return;

  const id = activeHangmanId();
  if (!id) return;
  const info = state.windows[id].hangman;
  if (!info) return;

  if (!info.started || !info.word) {
    if (ev.key === 'Enter') {
      ev.preventDefault();
      hangmanBasla(id);
    }
    return;
  }
  if (info.done) {
    if (ev.key === 'Enter') {
      ev.preventDefault();
      hangmanBasla(id);
    }
    return;
  }
  const letter = hangmanKeyFromEvent(ev);
  if (!letter) return;
  ev.preventDefault();
  guessLetter(id, letter);
});

function startHangmanRound(id, topicIdx, topicName) {
  const win = state.windows[id];
  if (!win) return;
  win.topicIdx = topicIdx;
  win.topicName = topicName || '';
  const game = document.getElementById(id + '-game');
  if (game) game.innerHTML = '<div class="loading" style="padding:8px;">Kelime seçiliyor...</div>';

  fetch('/api/hangman/word?topic=' + topicIdx)
    .then(r => r.json()).then(d => {
      if (!state.windows[id]) return;
      if (d.error) {
        document.getElementById(id + '-game').innerHTML =
          '<p style="color:#800;padding:8px;">' + escHtml(d.error) + '</p>';
        // keep board playable — reopen empty state
        if (win.hangman) {
          win.hangman.started = false;
          win.hangman.word = '';
          renderHangman(id);
        }
        return;
      }
      const word = toTrUpper(d.word || '');
      initHangmanGame(id, word, d.hint || d.en || '', topicIdx);
    });
}

function initHangmanGame(id, word, hint, topicIdx) {
  const wordUpper = toTrUpper(word);
  const prev = (state.windows[id] && state.windows[id].hangman) || {};
  const info = {
    word: wordUpper, hint: hint, topicIdx: topicIdx,
    guessed: [], wrong: 0, maxWrong: 9, done: false, id: id,
    score: (typeof prev.score === 'number' ? prev.score : HM_START_SCORE),
    started: true
  };
  state.windows[id].hangman = info;
  state.activeHangmanId = id;
  renderHangman(id);
}

function renderHangman(id) {
  const info = state.windows[id] && state.windows[id].hangman;
  if (!info) return;
  const started = !!info.started && !!info.word;
  const displayWord = started
    ? info.word.split('').map(c => info.guessed.includes(c) ? c : '_').join(' ')
    : '';
  const won = started && !displayWord.includes('_');
  const lost = started && info.wrong >= info.maxWrong;
  if (won || lost) info.done = true;

  const stage = started ? Math.min(info.wrong, 9) : 0;

  let html = `<div class="hm-main">`;

  // Upper: letter keys | banner + gallows/puan/acer
  html += `<div class="hm-upper">`;

  html += `<div class="hm-left">`;
  for (let r = 0; r < HM_KEYS.length; r++) {
    html += `<div class="hm-keyrow">`;
    for (let c = 0; c < 2; c++) {
      const letter = HM_KEYS[r][c];
      const idx = hmKeyIndex(letter);
      const used = started && info.guessed.includes(letter);
      // EXE idle board shows raised (normal) keys, not pressed
      const prefix = used ? 'p' : 'n';
      let onClick = '';
      let cls = '';
      if (!started) {
        cls = ' idle';
      } else if (used || info.done) {
        cls = ' used';
      } else {
        onClick = `guessLetter('${id}','${letter}')`;
      }
      html += `<img class="hm-key${cls}" width="25" height="25" src="/assets/keys/${prefix}_${String(idx).padStart(2,'0')}.png?v=8" ` +
        `alt="${letter}" title="${letter}" onclick="${onClick}">`;
    }
    html += `</div>`;
  }
  html += `</div>`;

  html += `<div class="hm-right">`;
  html += `<div class="hm-brand">`;
  html += `<img class="hm-brand-svg" src="/assets/MoonStar.svg?v=3" alt="MoonStar">`;
  html += `<div class="hm-brand-sub">“Özgün programlar yaratır”</div>`;
  html += `</div>`;
  html += `<div class="hm-status">`;
  html += `<div class="hm-status-row">`;
  html += `<div class="hm-gallows"><img width="52" height="76" src="/assets/hm_${stage}.png" alt=""></div>`;
  html += `<div class="hm-scorecol">`;
  html += `<div class="hm-scorelabel">Puan</div>`;
  html += `<div class="hm-scorebox" id="${id}-score">${info.score}</div>`;
  html += `</div></div>`;
  html += `<div class="hm-ad"><img width="98" height="98" src="/assets/extracted/img_052800_98x98_8bpp.png?v=1" alt="Acer"></div>`;
  html += `</div>`;
  html += `<div class="hm-wordbox">${displayWord}</div>`;
  if (won || lost) {
    const msg = won ? 'Kazandın!' : ('Kaybettin!  ' + info.word);
    html += `<div class="hm-result">${msg}</div>`;
  } else {
    html += `<div class="hm-result"></div>`;
  }
  html += `</div>`; // hm-right

  html += `</div>`; // hm-upper
  html += `<div class="hm-btns">`;
  html += `<img class="hm-btn" width="63" height="39" src="/assets/btn_sozluk.png" alt="Sözlük" title="Sözlük" onclick="hangmanSozluk('${id}')">`;
  html += `<img class="hm-btn" width="63" height="39" src="/assets/btn_basla.png" alt="Başla" title="Başla" onclick="hangmanBasla('${id}')">`;
  html += `<img class="hm-btn" width="63" height="39" src="/assets/btn_iptal.png" alt="İptal" title="İptal" onclick="closeWindow('${id}')">`;
  html += `</div>`;
  html += `</div>`; // hm-main

  document.getElementById(id+'-game').innerHTML = html;
}

function guessLetter(id, letter) {
  const info = state.windows[id] && state.windows[id].hangman;
  if (!info || !info.started || !info.word || info.done || info.guessed.includes(letter)) return;
  if (letter === '?') {
    // Hint: reveal one unrevealed letter (costs a wrong step)
    let revealed = false;
    for (const c of info.word) {
      if (!info.guessed.includes(c)) {
        info.guessed.push(c);
        revealed = true;
        break;
      }
    }
    if (revealed) {
      info.wrong = Math.min(info.wrong + 1, info.maxWrong);
      info.score = Math.max(0, info.score - 5);
    }
  } else {
    info.guessed.push(letter);
    if (!info.word.includes(letter)) {
      info.wrong++;
      info.score = Math.max(0, info.score - 10);
    } else {
      const hits = info.word.split('').filter(c => c === letter).length;
      info.score += hits * 10;
    }
  }
  if (info.wrong >= info.maxWrong || !info.word.split('').some(c => !info.guessed.includes(c))) {
    info.done = true;
    if (!info.word.split('').some(c => !info.guessed.includes(c))) {
      info.score += 50;
    }
  }
  renderHangman(id);
}

function openRawWindow(id, title, w, h, bodyHtml) {
  const workArea = document.getElementById('workArea');
  let html = `<div class="win-window" id="${id}" style="width:${w}px;height:${h}px;">`;
  html += `<div class="win-title"><img class="win-title-icon" src="/assets/moonstar_icon.png?v=2"><span class="win-title-text">${title}</span>`;
  html += `<div class="win-title-btns"><button onclick="closeWindow('${id}')">✕</button></div></div>`;
  html += `<div class="win-body" style="padding:4px;flex:1;display:flex;flex-direction:column;min-height:0;overflow:auto;">`;
  html += bodyHtml;
  html += `</div></div>`;
  workArea.insertAdjacentHTML('afterbegin', html);
  state.windows[id] = { type: 'raw', id: id };
}

// ─── Welcome Screen ───────────────────────────────────────────────────────
function welcomeBtnPress(img, pressed) {
  if (!img) return;
  img.src = pressed ? img.dataset.p : img.dataset.n;
}

function showWelcomeWindow() {
  closeAllWindows();
  const id = 'win-welcome';
  const workArea = document.getElementById('workArea');
  state.windows[id] = { type: 'welcome', id: id };

  // EXE module order (3×2): Denetim | TR→EN | Eş Anlam / Klavye | EN→TR | Adam Asma
  // Cache-bust so browsers don't keep old pressed bitmaps for btn_*.png
  const v = '3';
  const modules = [
    { label: 'Türkçe Denetim', base: 'btn_denetim', action: 'showCheckOptions()' },
    { label: 'Türkçe / İngilizce', base: 'btn_tr_en', action: "openWindow('tr-ing')" },
    { label: 'Türkçe Eş Anlamlılar', base: 'btn_esanlam', action: "openWindow('synonyms')" },
    { label: 'Klavye', base: 'btn_klavye', action: 'showKeyboardModule()' },
    { label: 'İngilizce / Türkçe', base: 'btn_en_tr', action: "openWindow('ing-tr')" },
    { label: 'Adam Asma', base: 'btn_adam_asma', action: "openWindow('quiz')" },
  ];

  let html = `<div class="win-window" id="${id}" style="width:372px;height:auto;">`;
  html += `<div class="win-title"><img class="win-title-icon" src="/assets/moonstar_icon.png?v=2"><span class="win-title-text">MoonStar Türkçe Dil Kılavuzu</span>`;
  html += `<div class="win-title-btns"><button onclick="closeWindow('${id}')">✕</button></div></div>`;
  html += `<div class="win-body welcome-body" style="padding:6px;">`;
  html += `<div class="welcome-panel">`;
  html += `<div class="welcome-grid">`;
  modules.forEach(m => {
    const n = `/assets/${m.base}.png?v=${v}`;
    const p = `/assets/${m.base}_p.png?v=${v}`;
    html += `<button type="button" class="welcome-btn" title="${m.label}" onclick="${m.action}"` +
      ` onpointerdown="welcomeBtnPress(this.querySelector('img'),true)"` +
      ` onpointerup="welcomeBtnPress(this.querySelector('img'),false)"` +
      ` onpointerleave="welcomeBtnPress(this.querySelector('img'),false)"` +
      ` onpointercancel="welcomeBtnPress(this.querySelector('img'),false)"` +
      ` onblur="welcomeBtnPress(this.querySelector('img'),false)">` +
      `<img src="${n}" width="104" height="50" data-n="${n}" data-p="${p}" alt="${m.label}" draggable="false">` +
      `</button>`;
  });
  html += `</div>`;
  html += `<div class="welcome-sep"></div>`;
  html += `<div class="welcome-banner">` +
    `<img src="/assets/extracted/img_052800_98x98_8bpp.png?v=${v}" class="welcome-banner-logo" width="98" height="98" alt="Acer">` +
    `<div class="welcome-banner-brand">` +
      `<img src="/assets/MoonStar.svg?v=${v}" class="welcome-banner-svg" alt="MoonStar">` +
      `<div class="welcome-banner-sub">“Özgün programlar yaratır”</div>` +
    `</div>` +
  `</div>`;
  html += `</div></div></div>`;
  workArea.insertAdjacentHTML('afterbegin', html);
}

function showKeyboardModule() {
  closeAllWindows();
  const id = 'win-kbd';
  if (document.getElementById(id)) return;
  const letters = 'ABCÇDEFGĞHIİJKLMNOÖPRSŞTUÜVYZ?';
  let keysHtml = '';
  for (let i = 0; i < letters.length; i++) {
    const p = String(i).padStart(2,'0');
    const ch = letters[i];
    keysHtml += `<img class="kbd-key" src="/assets/keys/n_${p}.png?v=3" ` +
      `data-n="/assets/keys/n_${p}.png?v=3" data-p="/assets/keys/p_${p}.png?v=3" ` +
      `alt="${ch}" title="${ch}" ` +
      `onpointerdown="this.src=this.dataset.p" ` +
      `onpointerup="this.src=this.dataset.n;selectKbdChar('${id}','${ch}')" ` +
      `onpointerleave="this.src=this.dataset.n" ` +
      `onpointercancel="this.src=this.dataset.n">`;
  }
  openRawWindow(id, 'Klavye', 250, 360, `
    <div style="padding:8px;display:flex;flex-direction:column;gap:8px;height:100%;">
      <div class="kbd-grid">${keysHtml}</div>
      <div class="group-box"><legend>Seçilen</legend>
        <input class="win-input" type="text" readonly id="${id}-char"
          style="width:100%;font-size:28px;text-align:center;background:#fff;color:#000;border:2px inset #c0c0c0;font-weight:700;font-family:inherit;">
      </div>
      <div style="text-align:right;flex-shrink:0;">
        <button class="win-btn primary" onclick="closeWindow('${id}')">Tamam</button>
        <button class="win-btn" onclick="closeWindow('${id}')">İptal</button>
      </div>
    </div>
  `);
}

function selectKbdChar(id, ch) {
  const el = document.getElementById(id+'-char');
  if (el) el.value = ch;
}

// ─── Stats Window ────────────────────────────────────────────────────────
function loadWindowStats(winId) {
  fetch('/api/stats').then(r=>r.json()).then(d=>{
    let html = '<div style="padding:4px;">';
    html += '<table style="margin-bottom:8px;"><tr><th>Veri</th><th>Kayıt Sayısı</th></tr>';
    const items = [
      ['İngilizce → Türkçe Sözlük', d.trk.total],
      ['Türkçe Leb Demeden', d.tur.total],
      ['Türkçe → İngilizce', d.rev.total],
      ['Eş Anlamlı Sözcükler', d.syn.total],
      ['Adam Asma', d.quiz.total],
    ];
    items.forEach(i => {
      html += `<tr><td>${i[0]}</td><td><b>${i[1].toLocaleString()}</b></td></tr>`;
    });
    html += '</table>';
    
    html += '<div class="group-box" style="margin-top:8px;"><legend>Konulara Göre Dağılım</legend>';
    html += '<table><tr><th>Konu</th><th>Kelime</th></tr>';
    d.topics.forEach(t => {
      html += `<tr><td>${t.name}</td><td>${t.count}</td></tr>`;
    });
    html += '</table></div></div>';
    document.getElementById(winId+'-body').innerHTML = html;
  });
}

// ─── Find Dialog ──────────────────────────────────────────────────────────
function showFindDialog() {
  closeAllMenus();
  document.getElementById('findDialog').classList.add('open');
  document.getElementById('findInput').value = '';
  document.getElementById('findResults').innerHTML = '';
  setTimeout(() => document.getElementById('findInput').focus(), 100);
}

function showReplaceDialog() {
  showFindDialog();
}

function doFind() {
  const q = document.getElementById('findInput').value;
  if (!q) { document.getElementById('findResults').innerHTML = '<div style="color:#800;">Kelime giriniz.</div>'; return; }
  
  const radios = document.getElementsByName('findType');
  let type = 'all';
  for (let r of radios) { if (r.checked) type = r.value || 'all'; }
  
  document.getElementById('findResults').innerHTML = '<div class="loading">Aranıyor...</div>';
  
  const promises = [];
  const labels = [];
  
  if (type === 'all' || type === 'trk') {
    promises.push(fetch('/api/trk/search?q='+encodeURIComponent(q)).then(r=>r.json()));
    labels.push('İngilizce → Türkçe');
  }
  if (type === 'all' || type === 'tur') {
    promises.push(fetch('/api/tur/search?q='+encodeURIComponent(q)).then(r=>r.json()));
    labels.push('Türkçe Leb Demeden');
  }
  if (type === 'all' || type === 'quiz') {
    promises.push(fetch('/api/quiz/search?q='+encodeURIComponent(q)).then(r=>r.json()));
      labels.push('Adam Asma');
    }
    
    if (type !== 'all' && type !== 'trk' && type !== 'tur' && type !== 'quiz') {
    // default to all
    Promise.all([
      fetch('/api/trk/search?q='+encodeURIComponent(q)).then(r=>r.json()),
      fetch('/api/tur/search?q='+encodeURIComponent(q)).then(r=>r.json()),
      fetch('/api/quiz/search?q='+encodeURIComponent(q)).then(r=>r.json()),
    ]).then(([trk, tur, quiz]) => {
      let html = '';
      let total = 0;
      if (trk.total > 0) {
        total += trk.total;
        html += '<div style="margin-top:4px;"><b>İngilizce → Türkçe</b></div>';
        trk.data.slice(0,20).forEach(e => { html += `<div style="padding:1px 4px;">${e.en} → ${e.tr}</div>`; });
      }
      if (tur.total > 0) {
        total += tur.total;
        html += '<div style="margin-top:4px;"><b>Türkçe Leb Demeden</b></div>';
        tur.data.slice(0,20).forEach(e => { html += `<div style="padding:1px 4px;">${e.word}</div>`; });
      }
      if (quiz.total > 0) {
        total += quiz.total;
        html += '<div style="margin-top:4px;"><b>Kelime Oyunu</b></div>';
        quiz.data.slice(0,20).forEach(e => { html += `<div style="padding:1px 4px;">[${e.topic}] ${e.en}</div>`; });
      }
      if (total === 0) html = '<div style="color:#666;">Sonuç bulunamadı.</div>';
      else html = `<div style="color:#444;margin-bottom:4px;">${total} sonuç</div>` + html;
      document.getElementById('findResults').innerHTML = html;
    });
    return;
  }
  
  Promise.all(promises).then(results => {
    let html = '';
    let total = 0;
    results.forEach((r, idx) => {
      if (r.total > 0) {
        total += r.total;
        html += `<div style="margin-top:4px;"><b>${labels[idx]}</b> (${r.total})</div>`;
        r.data.slice(0,20).forEach(e => {
          const text = e.en || e.word || '';
          const def = e.tr || e.def || e.synonyms || '';
          html += `<div style="padding:1px 4px;">${text} ${def ? '→ '+def : ''}</div>`;
        });
      }
    });
    if (total === 0) html = '<div style="color:#666;">Sonuç bulunamadı.</div>';
    else html = `<div style="color:#444;margin-bottom:4px;">${total} sonuç</div>` + html;
    document.getElementById('findResults').innerHTML = html;
  });
}

function closeDialog(id) {
  document.getElementById(id).classList.remove('open');
}

// ─── Check Options Dialog ─────────────────────────────────────────────────
function showCheckOptions() {
  closeAllWindows();
  const id = 'win-chk-' + (state.nextWindowId++);
  const workArea = document.getElementById('workArea');
  
  let html = `<div class="win-window" id="${id}" style="width:360px;height:280px;overflow:hidden;">`;
  html += `<div class="win-title"><img class="win-title-icon" src="/assets/moonstar_icon.png?v=2"><span class="win-title-text">Denetim Opsiyonlar</span>`;
  html += `<div class="win-title-btns"><button onclick="closeWindow('${id}')">✕</button></div></div>`;
  html += `<div class="win-body" style="padding:6px;flex:1;display:flex;flex-direction:column;min-height:0;overflow:hidden;">`;
  html += `<div class="group-box" style="flex:1;display:flex;flex-direction:column;min-height:0;margin:0 0 6px 0;"><legend>Denetim Seçenekleri</legend>`;
  html += `<div style="flex:1;overflow-y:auto;min-height:0;padding-top:4px;">`;
  const opts = [
    'Paragraf başı kontrol',
    'Bileşik isim denetimi',
    'Özel isim yumuşama denetimi',
    'Cins isim apostrof denetimi',
    'Öneri getirme',
    'Yazarken denetim',
    'Şapka denetimi',
  ];
  opts.forEach(o => {
    html += `<label style="display:block;margin:2px 0;font-size:13px;font-weight:600;"><input type="checkbox" checked> ${o}</label>`;
  });
  html += `</div></div>`;
  html += `<div style="text-align:right;flex-shrink:0;"><button class="win-btn primary" onclick="closeWindow('${id}')">Tamam</button></div>`;
  html += `</div></div>`;
  
  workArea.insertAdjacentHTML('afterbegin', html);
  state.windows[id] = { type: 'options', id: id };
}

// ─── Open Stats ───────────────────────────────────────────────────────────
function openStatsWindow() {
  closeAllMenus();
  openWindow('stats');
}

// ─── Open Quiz (Adam Asma) ──────────────────────────────────────────────
function openQuizWindow() {
  openWindow('quiz');
}

// ─── Show About ───────────────────────────────────────────────────────────
function showAbout() {
  closeAllMenus();
  document.getElementById('aboutDialog').classList.add('open');
}

// ─── Init ─────────────────────────────────────────────────────────────────
showWelcomeWindow();
</script>
</body>
</html>
"""


# ─── Auto‑reload helper ─────────────────────────────────────────────────────

def start_with_reload():
    import subprocess
    script_path = os.path.abspath(__file__)
    proc = None
    try:
        while True:
            if proc is not None:
                proc.terminate()
                try:
                    proc.wait(timeout=3)
                except:
                    proc.kill()
                    proc.wait()
                time.sleep(0.5)
            proc = subprocess.Popen(
                [sys.executable, script_path],
                cwd=SCRIPT_DIR
            )
            mtime = os.stat(script_path).st_mtime
            print(f"  🔄 --reload aktif: PID={proc.pid}")
            while True:
                time.sleep(0.8)
                new_mtime = os.stat(script_path).st_mtime
                if new_mtime != mtime:
                    print("\n  🔄 Değişiklik algılandı, yeniden başlatılıyor…")
                    break
    except KeyboardInterrupt:
        if proc:
            proc.terminate()
            proc.wait()
        print("\nSunucu durduruldu.")


# ─── Main ───────────────────────────────────────────────────────────────────

def main():
    import subprocess
    pid = subprocess.run(['lsof', '-ti', str(PORT)], capture_output=True, text=True).stdout.strip()
    if pid:
        print(f"  ⚠ Port {PORT} kullanımda (PID:{pid}), eski process sonlandırılıyor…")
        subprocess.run(['kill', '-9', pid], capture_output=True)
        time.sleep(0.3)

    http.server.HTTPServer.allow_reuse_address = True
    server = http.server.HTTPServer(("0.0.0.0", PORT), MoonStarHandler)

    def shutdown(signum=None, frame=None):
        print("\nSunucu durduruldu.")
        server.shutdown()
        server.server_close()
        sys.exit(0)

    signal.signal(signal.SIGTERM, shutdown)

    print(f"\n🌙 MoonStar Veri Gezgini çalışıyor:")
    print(f"   http://localhost:{PORT}")
    print(f"\n   Sözlükler: İng→Tr ({len(TRK_DATA)}), Tr→Tr ({len(TUR_DATA)}), EşAnlam ({len(SYN_DATA)})")
    print(f"   Kelime Oyunu: {len(QUIZ_DATA)} kelime, {len([t for t in TOPIC_NAMES if len(t) > 1])} konu")
    print(f"\n   Çıkmak için Ctrl+C\n")
    try:
        server.serve_forever()
    except KeyboardInterrupt:
        shutdown()


if __name__ == "__main__":
    if "--reload" in sys.argv:
        start_with_reload()
    else:
        main()
